[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.dependencies]
console = "0.15"
serde_yaml = "0.9.34"
tempfile = "3.17.1"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
