[package]
name = "selfie"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.87"
config = { version = "0.15.9", features = ["yaml"] }
etcetera = "0.10.0"
num_cpus = "1.16.0"
serde = { version = "1.0.218", features = ["derive"] }
shellexpand = "3.1.0"
thiserror = "2.0.11"

[dev-dependencies]
mockall = "0.13.1"
serde_yaml = "0.9.34"
tempfile = "3.17.1"

[target.'cfg(unix)'.dev-dependencies]
nix = { version = "0.29", features = ["user"] }
